### ISSUE TITLE
IP Theft

### ISSUE THREAD

**Issue by nvzqz** [Hermitter/dotfiles#1]
I don't have proof but my dotfiles inspired your scripts, which is theft of my intellectual property. Or something.

![image](https://user-images.githubusercontent.com/10367662/104145303-6a61ed80-5394-11eb-8154-89ccdb8e3969.png)

**Comment by Hermitter** [comment]
Excuse me, your dotfiles are partially stolen from my dotfiles
![image](https://user-images.githubusercontent.com/17160717/104145379-cc225780-5394-11eb-91c8-48612db3f4cb.png)
